config/routes.rb
Productos::Application.routes.draw do

  resources :categories

  resources :images

  resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product
  
  has_attached_file :image, :styles => { :medium => "300x300>", :small => "48x48>", :thumb => "100x100>" }
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :images
  
  has_attached_file :image, :styles => { :medium => "300x300>", :small => "48x48>", :thumb => "100x100>" }
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.xml
  def index
    @images = Image.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.xml
  def index
    @products = Product.all
    @categories =  Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_category %><br />
    <%= f.text_field :name_category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name_category %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name category:</b>
  <%= @category.name_category %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/images/_form.html.erb
<%= form_for(@image,  :html => { :multipart => true }) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br />
	<%= f.file_field :image %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>Listing images</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Image file name</th>
    <th>Image content type</th>
    <th>Image file size</th>
    <th>Image upadte at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @images.each do |image| %>
  <tr>
    <td><%= image.product_id %></td>
    <td><%= image.image_file_name %></td>
    <td><%= image.image_content_type %></td>
    <td><%= image.image_file_size %></td>
    <td><%= image.image_upadte_at %></td>
    <td><%= link_to 'Show', image %></td>
    <td><%= link_to 'Edit', edit_image_path(image) %></td>
    <td><%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %></td>

	<td>	<% if image.image? %>
		 <%= image_tag image.image.url(:medium) %>
		<br />
		 <%= link_to image.image.url, image.image.url %>
		<% end %> </td>
		
  </tr>


<% end %>
</table>

<br />

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @image.product_id %>
</p>

<p>
  <b>Image file name:</b>
  <%= @image.image_file_name %>
</p>

<p>
  <b>Image content type:</b>
  <%= @image.image_content_type %>
</p>

<p>
  <b>Image file size:</b>
  <%= @image.image_file_size %>
</p>

<p>
  <b>Image upadte at:</b>
  <%= @image.image_upadte_at %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Productos</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_product %><br />
    <%= f.text_field :name_product %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :expration %><br />
    <%= f.text_area :expration %>
  </div>
  <div class="field">
    <%= f.label :conservation %><br />
    <%= f.text_area :conservation %>
  </div>
  <div class="field">
    <%= f.label :format %><br />
    <%= f.text_area :format %>
  </div>
  <div class="field">
    <%= f.label :specialformat %><br />
    <%= f.text_area :specialformat %>
  </div>
  <div class="field">
    <%= f.label :preparation %><br />
    <%= f.text_area :preparation %>
  </div>
  <div class="field">
    <%= f.label :moreinfo %><br />
    <%= f.text_area :moreinfo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Documento sin título</title>
<link href="general.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div class="contenedor">
  <div class="cabecera">
    <div class="menu">
    <ul>
    <li><a href="index.html">LAKET</a></li>
	 <li><a href="pnpspace.html">PRODUCTOS</a></li>
	 <li><a href="miembros.html">CANALES DE DISTRIBUCIÓN</a></li>
	 <li><a href="pnpschool.html">BLOG</a></li>
     <li><a href="pnpschool.html">CONTACTO</a></li>
    </ul>
    </div>
    <div class="iconos"><a href="https://www.facebook.com/profile.php?id=100002223007512" target="_blank"><img src="images/ico_facebook.png" width="63" height="64" /></a><img src="images/ico_twitter.png" width="63" height="64" /><img src="images/ico_rss.png" width="63" height="64" /></div>
  </div>
  <div class="cuerpo">
    <div class="colleft">
      <div class="imagebig"><img src="images/img_portada.jpg" width="584" height="205" /></div>
      <div class="spacer"></div>
      <div class="titportada">
        <h1>NUESTROS PRODUCTOS</h1>
      </div>
      <div class="textportada"> 
      <h3>El sabor de la tradición</h3>
      <p class="texto">&nbsp;</p>
      <p class="texto">Nullam quis sem ante, quis dapibus elit. Cras cursus purus vitae quam congue sed aliquam ligula iaculis. Sed sollicitudin facilisis magna vel auctor. Proin purus lectus, gravida ac ultricies a, bibendum ut dui. Suspendisse scelerisque lobortis ullamcorper. Sed laoreet luctus suscipit. Curabitur urna ante, commodo in dapibus mattis, facilisis vel tellus. Nunc aliquet egestas sem, nec tempor est imperdiet condimentum. Nam tellus nibh, tristique non placerat eu, ornare vel sem.</p>
        <p class="texto">&nbsp;</p>
        
      <p class="texto">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis sem ante, quis dapibus elit. Cras cursus purus vitae quam congue sed aliquam ligula iaculis. Sed sollicitudin facilisis magna vel auctor. Proin purus lectus, gravida ac ultricies a, bibendum ut dui. Suspendisse scelerisque lobortis ullamcorper. Sed laoreet luctus suscipit. Curabitur urna ante, commodo in dapibus mattis, facilisis vel tellus.</p> </div>
       <div class="titportada">
        <h1>NUESTROS PRODUCTOS</h1>
      </div>
       
    
    
    
    <div class="galeria">
    <div class="img_galeria"><img src="images/img_portada.jpg" width="184" height="184" /></div>
    <div class="img_galeria"><img src="images/img_portada.jpg" width="184" height="184" /></div>
    <div class="img_galeria2"><img src="images/img_portada.jpg" width="184" height="184" /></div>    
    </div>
    <div class="spacer"></div>
    
    
    
    
    </div>
    <div class="colright">
    <div class="blog">
      <h2>BLOG: ÚLTIMAS ENTRADAS</h2>
      <h4>&nbsp;</h4>
      <h4><a href="tepes">Loren ipsum dolor sit amet</a></h4>
      <p class="textomini">&nbsp;</p>
      <p class="textomini">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis sem ante, quis dapibus elit. Cras cursus purus vitae quam congue sed aliquam ligula iaculis. Sed sollicitudin facilisis magna vel auctor. Proin purus lectus, gravida ac ultricies a, bibendum ut dui. Suspendisse scelerisque lobortis ullamcorper. Sed laoreet luctus suscipit. Curabitur urna ante, commodo in dapibus mattis, facilisis vel tellus.</p>
      <p class="textomini"><img src="images/separador.gif" width="295" height="22" /></p>
      <h4><a href="patas">Loren ipsum dolor sit amet</a></h4>
      <p class="textomini">&nbsp;</p>
      <p class="textomini">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis sem ante, quis dapibus elit. Cras cursus purus vitae quam congue sed aliquam ligula iaculis. Sed sollicitudin facilisis magna vel auctor. Proin purus lectus, gravida ac ultricies a, bibendum ut dui. Suspendisse scelerisque lobortis ullamcorper. Sed laoreet luctus suscipit. Curabitur urna ante, commodo in dapibus mattis, facilisis vel tellus.</p>
      <p class="textomini"><img src="images/separador.gif" width="295" height="22" /></p>
      <h4>Loren ipsum dolor sit amet</h4>
      <p class="textomini">&nbsp;</p>
      <p class="textomini">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis sem ante, quis dapibus elit. Cras cursus purus vitae quam congue sed aliquam ligula iaculis. Sed sollicitudin facilisis magna vel auctor. Proin purus lectus, gravida ac ultricies a, bibendum ut dui. Suspendisse scelerisque lobortis ullamcorper. Sed laoreet luctus suscipit. Curabitur urna ante, commodo in dapibus mattis, facilisis vel tellus.</p>
      <p class="textomini"><img src="images/separador.gif" width="295" height="22" /></p>
      <h4>Loren ipsum dolor sit amet</h4>
      <p class="textomini">&nbsp;</p>
      <p class="textomini">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis sem ante, quis dapibus elit. Cras cursus purus vitae quam congue sed aliquam ligula iaculis. Sed sollicitudin facilisis magna vel auctor. Proin purus lectus, gravida ac ultricies a, bibendum ut dui. Suspendisse scelerisque lobortis ullamcorper. Sed laoreet luctus suscipit. Curabitur urna ante, commodo in dapibus mattis, facilisis vel tellus.</p>
      <p class="textomini"><img src="images/ver.png" width="295" height="30" /></p>
      </div>
      <div class="spacer2"></div>
    </div>
  </div>
  <div class="pie"><a href="http://www.alimentosartesanos.com" target="_blank"><img src="images/logo_reyno.png" width="103" height="91" /><img src="images/logo_artesanos.png" width="92" height="94" /></a>
 <div class="creditos"><p class="txtcreditos">©2011 laket artesanos | Pol.Utzubar Calle E P-10 31839 Arbizu (Navarra)  | <a href="legoland">nota legal</a></p>
 </div> 
 </div>
</div>
</body>
</html>




<h1>Listing products</h1>

<table>
  <tr>
    <th>Name product</th>
    <th>Category</th>
    <th>Ingredients</th>
    <th>Expration</th>
    <th>Conservation</th>
    <th>Format</th>
    <th>Specialformat</th>
    <th>Preparation</th>
    <th>Moreinfo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name_product %></td>
    <td><%= product.categories.category_name %></td>
    <td><%= product.ingredients %></td>
    <td><%= product.expration %></td>
    <td><%= product.conservation %></td>
    <td><%= product.format %></td>
    <td><%= product.specialformat %></td>
    <td><%= product.preparation %></td>
    <td><%= product.moreinfo %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %></td>
<% product.images.each do |image| %>
<td>sssaaa<%= image.image_file_name %></td>
<td>	<% if image.image? %>
	 <%= image_tag image.image.url(:medium) %>
	<br />
	 <%= link_to image.image.url, image.image.url %>
	<% end %> </td>

<% end %>




  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name product:</b>
  <%= @product.name_product %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category_id %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @product.ingredients %>
</p>

<p>
  <b>Expration:</b>
  <%= @product.expration %>
</p>

<p>
  <b>Conservation:</b>
  <%= @product.conservation %>
</p>

<p>
  <b>Format:</b>
  <%= @product.format %>
</p>

<p>
  <b>Specialformat:</b>
  <%= @product.specialformat %>
</p>

<p>
  <b>Preparation:</b>
  <%= @product.preparation %>
</p>

<p>
  <b>Moreinfo:</b>
  <%= @product.moreinfo %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>